services:
  postgres:
    image: postgres:13
    container_name: in6av_postgres
    environment:
      POSTGRES_USER: IN6AV
      POSTGRES_PASSWORD: In6avKnl!
      POSTGRES_DB: kinal_sports_users
    ports:
<<<<<<< HEAD
      - "5436:5432"
=======
      - "5430:5432"
>>>>>>> ft/eddy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: